version: "3.7"
services:
  ruby_dev:
    build: .
    container_name: ruby_container
    volumes:
      - ./:/home/app
    ports: 
      - 3000:3000
    command: rails server -b 0.0.0.0
    entrypoint: ./docker-entrypoint.sh
